services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "20757:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://f1757:3wRWWwZHj3@192.168.1.1/db_f1757
      - ENVIRONMENT=production
    networks:
      - squads-network
    volumes:
      - ./backend:/app
    restart: unless-stopped


networks:
  squads-network:
    driver: bridge
