services:
  # Database service (SQLite for development, can be changed to PostgreSQL for production)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: squads_db
      POSTGRES_USER: squads_user
      POSTGRES_PASSWORD: squads_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - squads-network

  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://squads_user:squads_password@db:5432/squads_db
      - ENVIRONMENT=production
    depends_on:
      - db
    networks:
      - squads-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  squads-network:
    driver: bridge
