services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "20757:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - squads-network
    volumes:
      - ./backend:/app
    restart: unless-stopped


networks:
  squads-network:
    driver: bridge
