"""init migration

Revision ID: 8a42b2ab6f72
Revises: 
Create Date: 2025-06-30 00:09:28.523357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a42b2ab6f72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('score_history', 'match_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'squads', 'users', ['owner_id'], ['user_id'])
    op.create_foreign_key(None, 'user_squads', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_squads', type_='foreignkey')
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.alter_column('score_history', 'match_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_table('users')
    # ### end Alembic commands ###
