"""add owner_id to squads

Revision ID: a72f01740480
Revises: 8e9fbbb31892
Create Date: 2025-06-17 21:41:16.921218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72f01740480'
down_revision: Union[str, None] = '8e9fbbb31892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('score_history', 'match_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('squads', sa.Column('owner_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'squads', 'users', ['owner_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'squads', type_='foreignkey')
    op.drop_column('squads', 'owner_id')
    op.alter_column('score_history', 'match_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
