"""init migration

Revision ID: c49f3bf279e0
Revises: 
Create Date: 2025-06-18 23:32:57.258974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49f3bf279e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('squads',
    sa.Column('squad_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('squad_id')
    )
    op.create_table('players',
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('squad_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('base_score', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('tournaments',
    sa.Column('squad_id', sa.String(length=36), nullable=True),
    sa.Column('tournament_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_table('matches',
    sa.Column('squad_id', sa.String(length=36), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tournament_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('user_squads',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('squad_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'squad_id')
    )
    op.create_table('score_history',
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'match_id')
    )
    op.create_table('teams',
    sa.Column('squad_id', sa.String(length=36), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('team_players',
    sa.Column('squad_id', sa.String(length=36), nullable=True),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'team_id', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_players')
    op.drop_table('teams')
    op.drop_table('score_history')
    op.drop_table('user_squads')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('players')
    op.drop_table('squads')
    op.drop_table('users')
    # ### end Alembic commands ###
