"""add owner_id to squads

Revision ID: f243fd611bf0
Revises: 8e9fbbb31892
Create Date: 2025-06-17 21:37:35.679791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f243fd611bf0'
down_revision: Union[str, None] = '8e9fbbb31892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add owner_id column to squads table
    op.add_column('squads', sa.Column('owner_id', sa.String(length=36), nullable=True))
    
    # Create foreign key constraint
    op.create_foreign_key(
        'fk_squads_owner_id_users',
        'squads', 'users',
        ['owner_id'], ['user_id']
    )
    
    # Make owner_id non-nullable after adding the column
    op.alter_column('squads', 'owner_id',
                    existing_type=sa.String(length=36),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint
    op.drop_constraint('fk_squads_owner_id_users', 'squads', type_='foreignkey')
    
    # Drop the owner_id column
    op.drop_column('squads', 'owner_id')
    # ### end Alembic commands ###
